Update parse_settings.py
******@******:~/nebula-setup$ sudo ./create_db.sh
  File "./support/parse_settings.py", line 22
    print config[sys.argv[1]]
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(config[sys.argv[1]])?
  File "./support/parse_settings.py", line 22
    print config[sys.argv[1]]
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(config[sys.argv[1]])?
  File "./support/parse_settings.py", line 22
    print config[sys.argv[1]]
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(config[sys.argv[1]])?

DB connection params unspecified